# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'widget.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(1522, 972)
        self.Img_view1 = QLabel(Widget)
        self.Img_view1.setObjectName(u"Img_view1")
        self.Img_view1.setGeometry(QRect(40, 40, 480, 270))
        self.Img_view1.setFrameShape(QFrame.Box)
        self.Img_view2 = QLabel(Widget)
        self.Img_view2.setObjectName(u"Img_view2")
        self.Img_view2.setGeometry(QRect(520, 40, 480, 270))
        self.Img_view2.setFrameShape(QFrame.Box)
        self.Img_view3 = QLabel(Widget)
        self.Img_view3.setObjectName(u"Img_view3")
        self.Img_view3.setGeometry(QRect(1000, 40, 480, 270))
        self.Img_view3.setFrameShape(QFrame.Box)
        self.map_change = QPushButton(Widget)
        self.map_change.setObjectName(u"map_change")
        self.map_change.setGeometry(QRect(860, 370, 131, 41))
        self.line = QFrame(Widget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 350, 1521, 21))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.frame_ownship = QFrame(Widget)
        self.frame_ownship.setObjectName(u"frame_ownship")
        self.frame_ownship.setGeometry(QRect(860, 420, 651, 141))
        self.frame_ownship.setFrameShape(QFrame.StyledPanel)
        self.frame_ownship.setFrameShadow(QFrame.Raised)
        self.IN_Ownship_Alt = QLabel(self.frame_ownship)
        self.IN_Ownship_Alt.setObjectName(u"IN_Ownship_Alt")
        self.IN_Ownship_Alt.setGeometry(QRect(470, 50, 107, 17))
        self.IN_Ownship_Head = QLabel(self.frame_ownship)
        self.IN_Ownship_Head.setObjectName(u"IN_Ownship_Head")
        self.IN_Ownship_Head.setGeometry(QRect(470, 70, 107, 17))
        self.label_6 = QLabel(self.frame_ownship)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(340, 70, 111, 17))
        self.label_7 = QLabel(self.frame_ownship)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(340, 50, 107, 17))
        self.label_8 = QLabel(self.frame_ownship)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(340, 90, 111, 17))
        self.label_9 = QLabel(self.frame_ownship)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(340, 110, 111, 17))
        self.IN_Ownship_Hor_vel = QLabel(self.frame_ownship)
        self.IN_Ownship_Hor_vel.setObjectName(u"IN_Ownship_Hor_vel")
        self.IN_Ownship_Hor_vel.setGeometry(QRect(470, 90, 121, 17))
        self.IN_Ownship_Ver_vel = QLabel(self.frame_ownship)
        self.IN_Ownship_Ver_vel.setObjectName(u"IN_Ownship_Ver_vel")
        self.IN_Ownship_Ver_vel.setGeometry(QRect(470, 110, 121, 17))
        self.label_10 = QLabel(self.frame_ownship)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(19, 108, 107, 17))
        self.label_11 = QLabel(self.frame_ownship)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 70, 107, 17))
        self.IN_Ownship_y = QLabel(self.frame_ownship)
        self.IN_Ownship_y.setObjectName(u"IN_Ownship_y")
        self.IN_Ownship_y.setGeometry(QRect(149, 108, 107, 17))
        self.IN_Ownship_lat = QLabel(self.frame_ownship)
        self.IN_Ownship_lat.setObjectName(u"IN_Ownship_lat")
        self.IN_Ownship_lat.setGeometry(QRect(150, 50, 107, 17))
        self.label_12 = QLabel(self.frame_ownship)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 29, 107, 17))
        self.label_13 = QLabel(self.frame_ownship)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 50, 107, 17))
        self.IN_Ownship_lon = QLabel(self.frame_ownship)
        self.IN_Ownship_lon.setObjectName(u"IN_Ownship_lon")
        self.IN_Ownship_lon.setGeometry(QRect(150, 70, 107, 17))
        self.IN_Ownship_ICAO = QLabel(self.frame_ownship)
        self.IN_Ownship_ICAO.setObjectName(u"IN_Ownship_ICAO")
        self.IN_Ownship_ICAO.setGeometry(QRect(149, 29, 103, 17))
        self.IN_Ownship_x = QLabel(self.frame_ownship)
        self.IN_Ownship_x.setObjectName(u"IN_Ownship_x")
        self.IN_Ownship_x.setGeometry(QRect(149, 88, 107, 17))
        self.label_14 = QLabel(self.frame_ownship)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(19, 88, 107, 17))
        self.IN_Ownship_Call = QLabel(self.frame_ownship)
        self.IN_Ownship_Call.setObjectName(u"IN_Ownship_Call")
        self.IN_Ownship_Call.setGeometry(QRect(469, 30, 103, 17))
        self.label_15 = QLabel(self.frame_ownship)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(340, 30, 107, 17))
        self.label = QLabel(self.frame_ownship)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(270, 50, 41, 17))
        self.label_2 = QLabel(self.frame_ownship)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(270, 70, 41, 17))
        self.label_3 = QLabel(self.frame_ownship)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(270, 90, 41, 17))
        self.label_4 = QLabel(self.frame_ownship)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(270, 110, 41, 17))
        self.label_5 = QLabel(self.frame_ownship)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(600, 50, 41, 17))
        self.label_26 = QLabel(self.frame_ownship)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(600, 70, 41, 17))
        self.label_27 = QLabel(self.frame_ownship)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(600, 90, 41, 17))
        self.label_28 = QLabel(self.frame_ownship)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(600, 110, 41, 17))
        self.label_37 = QLabel(self.frame_ownship)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(6, 5, 201, 17))
        self.label_37.setFrameShape(QFrame.NoFrame)
        self.frame_intruder = QFrame(Widget)
        self.frame_intruder.setObjectName(u"frame_intruder")
        self.frame_intruder.setGeometry(QRect(860, 570, 651, 141))
        self.frame_intruder.setFrameShape(QFrame.StyledPanel)
        self.frame_intruder.setFrameShadow(QFrame.Raised)
        self.IN_Intruder_Alt = QLabel(self.frame_intruder)
        self.IN_Intruder_Alt.setObjectName(u"IN_Intruder_Alt")
        self.IN_Intruder_Alt.setGeometry(QRect(470, 52, 107, 17))
        self.IN_Intruder_Head = QLabel(self.frame_intruder)
        self.IN_Intruder_Head.setObjectName(u"IN_Intruder_Head")
        self.IN_Intruder_Head.setGeometry(QRect(470, 72, 107, 17))
        self.label_16 = QLabel(self.frame_intruder)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(340, 72, 111, 17))
        self.label_17 = QLabel(self.frame_intruder)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(340, 52, 107, 17))
        self.label_18 = QLabel(self.frame_intruder)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(340, 92, 111, 17))
        self.label_19 = QLabel(self.frame_intruder)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(340, 112, 111, 17))
        self.IN_Intruder_Hor_vel = QLabel(self.frame_intruder)
        self.IN_Intruder_Hor_vel.setObjectName(u"IN_Intruder_Hor_vel")
        self.IN_Intruder_Hor_vel.setGeometry(QRect(470, 92, 121, 17))
        self.IN_Intruder_Ver_vel = QLabel(self.frame_intruder)
        self.IN_Intruder_Ver_vel.setObjectName(u"IN_Intruder_Ver_vel")
        self.IN_Intruder_Ver_vel.setGeometry(QRect(470, 112, 121, 17))
        self.label_20 = QLabel(self.frame_intruder)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(19, 110, 107, 17))
        self.label_21 = QLabel(self.frame_intruder)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 72, 107, 17))
        self.IN_Intruder_y = QLabel(self.frame_intruder)
        self.IN_Intruder_y.setObjectName(u"IN_Intruder_y")
        self.IN_Intruder_y.setGeometry(QRect(149, 110, 107, 17))
        self.IN_Intruder_lat = QLabel(self.frame_intruder)
        self.IN_Intruder_lat.setObjectName(u"IN_Intruder_lat")
        self.IN_Intruder_lat.setGeometry(QRect(150, 52, 107, 17))
        self.label_22 = QLabel(self.frame_intruder)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 31, 107, 17))
        self.label_23 = QLabel(self.frame_intruder)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(20, 52, 107, 17))
        self.IN_Intruder_lon = QLabel(self.frame_intruder)
        self.IN_Intruder_lon.setObjectName(u"IN_Intruder_lon")
        self.IN_Intruder_lon.setGeometry(QRect(150, 72, 107, 17))
        self.IN_Intruder_ICAO = QLabel(self.frame_intruder)
        self.IN_Intruder_ICAO.setObjectName(u"IN_Intruder_ICAO")
        self.IN_Intruder_ICAO.setGeometry(QRect(149, 31, 103, 17))
        self.IN_Intruder_x = QLabel(self.frame_intruder)
        self.IN_Intruder_x.setObjectName(u"IN_Intruder_x")
        self.IN_Intruder_x.setGeometry(QRect(149, 90, 107, 17))
        self.label_24 = QLabel(self.frame_intruder)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(19, 90, 107, 17))
        self.IN_Intruder_Call = QLabel(self.frame_intruder)
        self.IN_Intruder_Call.setObjectName(u"IN_Intruder_Call")
        self.IN_Intruder_Call.setGeometry(QRect(469, 32, 103, 17))
        self.label_25 = QLabel(self.frame_intruder)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(340, 32, 107, 17))
        self.label_29 = QLabel(self.frame_intruder)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(270, 52, 41, 17))
        self.label_30 = QLabel(self.frame_intruder)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(270, 72, 41, 17))
        self.label_31 = QLabel(self.frame_intruder)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(270, 112, 41, 17))
        self.label_32 = QLabel(self.frame_intruder)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(600, 52, 41, 17))
        self.label_33 = QLabel(self.frame_intruder)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(600, 112, 41, 17))
        self.label_34 = QLabel(self.frame_intruder)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(600, 92, 41, 17))
        self.label_35 = QLabel(self.frame_intruder)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(600, 72, 41, 17))
        self.label_36 = QLabel(self.frame_intruder)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(270, 92, 41, 17))
        self.label_38 = QLabel(self.frame_intruder)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 6, 201, 17))
        self.label_38.setFrameShape(QFrame.NoFrame)
        self.tabWidget = QTabWidget(Widget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(860, 720, 651, 241))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.verticalLayoutWidget = QWidget(self.tab)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 10, 631, 191))
        self.DistanceLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.DistanceLayout.setSpacing(6)
        self.DistanceLayout.setContentsMargins(11, 11, 11, 11)
        self.DistanceLayout.setObjectName(u"DistanceLayout")
        self.DistanceLayout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget.addTab(self.tab, "")
        self.map_change_Down = QPushButton(Widget)
        self.map_change_Down.setObjectName(u"map_change_Down")
        self.map_change_Down.setGeometry(QRect(1000, 370, 131, 41))
        self.layoutWidget = QWidget(Widget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(1270, 10, 211, 19))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_39 = QLabel(self.layoutWidget)
        self.label_39.setObjectName(u"label_39")

        self.horizontalLayout.addWidget(self.label_39)

        self.CurrentTime = QLabel(self.layoutWidget)
        self.CurrentTime.setObjectName(u"CurrentTime")

        self.horizontalLayout.addWidget(self.CurrentTime)

        self.tabWidget_2 = QTabWidget(Widget)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(20, 370, 821, 591))
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.MAP = QLabel(self.tab_5)
        self.MAP.setObjectName(u"MAP")
        self.MAP.setGeometry(QRect(10, 10, 801, 541))
        self.MAP.setFrameShape(QFrame.Box)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.verticalLayoutWidget_2 = QWidget(self.tab_3)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(10, 10, 801, 541))
        self.visualization_layout = QVBoxLayout(self.verticalLayoutWidget_2)
        self.visualization_layout.setSpacing(6)
        self.visualization_layout.setContentsMargins(11, 11, 11, 11)
        self.visualization_layout.setObjectName(u"visualization_layout")
        self.visualization_layout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.IN_ROS_TIME = QLabel(Widget)
        self.IN_ROS_TIME.setObjectName(u"IN_ROS_TIME")
        self.IN_ROS_TIME.setGeometry(QRect(1090, 10, 191, 17))
        self.label_41 = QLabel(Widget)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(980, 10, 101, 17))
        self.label_42 = QLabel(Widget)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(1140, 370, 191, 40))
        self.IN_distance = QLabel(Widget)
        self.IN_distance.setObjectName(u"IN_distance")
        self.IN_distance.setGeometry(QRect(1340, 370, 131, 41))
        self.Image_Left = QLabel(Widget)
        self.Image_Left.setObjectName(u"Image_Left")
        self.Image_Left.setGeometry(QRect(90, 310, 381, 41))
        self.Close_Left = QPushButton(Widget)
        self.Close_Left.setObjectName(u"Close_Left")
        self.Close_Left.setGeometry(QRect(420, 320, 41, 25))
        self.Open_Left = QPushButton(Widget)
        self.Open_Left.setObjectName(u"Open_Left")
        self.Open_Left.setGeometry(QRect(370, 320, 41, 25))
        self.Close_Right = QPushButton(Widget)
        self.Close_Right.setObjectName(u"Close_Right")
        self.Close_Right.setGeometry(QRect(1390, 320, 41, 25))
        self.Image_Right = QLabel(Widget)
        self.Image_Right.setObjectName(u"Image_Right")
        self.Image_Right.setGeometry(QRect(1070, 310, 361, 41))
        self.Open_Right = QPushButton(Widget)
        self.Open_Right.setObjectName(u"Open_Right")
        self.Open_Right.setGeometry(QRect(1340, 320, 41, 25))
        self.Image_Front = QLabel(Widget)
        self.Image_Front.setObjectName(u"Image_Front")
        self.Image_Front.setGeometry(QRect(570, 310, 381, 41))
        self.Open_Front = QPushButton(Widget)
        self.Open_Front.setObjectName(u"Open_Front")
        self.Open_Front.setGeometry(QRect(820, 320, 41, 25))
        self.Close_Front = QPushButton(Widget)
        self.Close_Front.setObjectName(u"Close_Front")
        self.Close_Front.setGeometry(QRect(870, 320, 41, 25))
        self.tabWidget.raise_()
        self.layoutWidget.raise_()
        self.frame_ownship.raise_()
        self.Img_view1.raise_()
        self.Img_view2.raise_()
        self.Img_view3.raise_()
        self.map_change.raise_()
        self.line.raise_()
        self.frame_intruder.raise_()
        self.map_change_Down.raise_()
        self.tabWidget_2.raise_()
        self.IN_ROS_TIME.raise_()
        self.label_41.raise_()
        self.label_42.raise_()
        self.IN_distance.raise_()
        self.Image_Left.raise_()
        self.Close_Left.raise_()
        self.Open_Left.raise_()
        self.Close_Right.raise_()
        self.Image_Right.raise_()
        self.Open_Right.raise_()
        self.Image_Front.raise_()
        self.Open_Front.raise_()
        self.Close_Front.raise_()

        self.retranslateUi(Widget)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.Img_view1.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\"><span style=\" color:#2e3436;\">Image_view1</span></p></body></html>", None))
        self.Img_view2.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\"><span style=\" color:#2e3436;\">Image_view2</span></p></body></html>", None))
        self.Img_view3.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\"><span style=\" color:#2e3436;\">Image_view3</span></p></body></html>", None))
        self.map_change.setText(QCoreApplication.translate("Widget", u"MAP SCALE UP", None))
        self.IN_Ownship_Alt.setText(QCoreApplication.translate("Widget", u"Ownship_Alt", None))
        self.IN_Ownship_Head.setText(QCoreApplication.translate("Widget", u"Ownship_Head", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"Heading             :", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"Altitude             :", None))
        self.label_8.setText(QCoreApplication.translate("Widget", u"Hor_velocity     :", None))
        self.label_9.setText(QCoreApplication.translate("Widget", u"Ver_Velocity     :", None))
        self.IN_Ownship_Hor_vel.setText(QCoreApplication.translate("Widget", u"Ownship_Hor_vel", None))
        self.IN_Ownship_Ver_vel.setText(QCoreApplication.translate("Widget", u"Ownship_Ver_vel", None))
        self.label_10.setText(QCoreApplication.translate("Widget", u"ECEF_East         :", None))
        self.label_11.setText(QCoreApplication.translate("Widget", u"Logitude            :", None))
        self.IN_Ownship_y.setText(QCoreApplication.translate("Widget", u"Ownship_y", None))
        self.IN_Ownship_lat.setText(QCoreApplication.translate("Widget", u"Ownship_lat", None))
        self.label_12.setText(QCoreApplication.translate("Widget", u"ICAO_number  :", None))
        self.label_13.setText(QCoreApplication.translate("Widget", u"Latitude             :", None))
        self.IN_Ownship_lon.setText(QCoreApplication.translate("Widget", u"Ownship_lon", None))
        self.IN_Ownship_ICAO.setText(QCoreApplication.translate("Widget", u"Ownship_ICAO", None))
        self.IN_Ownship_x.setText(QCoreApplication.translate("Widget", u"Ownship_x", None))
        self.label_14.setText(QCoreApplication.translate("Widget", u"ECEF_North      :", None))
        self.IN_Ownship_Call.setText(QCoreApplication.translate("Widget", u"Ownship_call", None))
        self.label_15.setText(QCoreApplication.translate("Widget", u"Call_sign            :", None))
        self.label.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_26.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_27.setText(QCoreApplication.translate("Widget", u"[m/s]", None))
        self.label_28.setText(QCoreApplication.translate("Widget", u"[m/s]", None))
        self.label_37.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic;\">OWNSHIP  INFORMATION</span></p></body></html>", None))
        self.IN_Intruder_Alt.setText(QCoreApplication.translate("Widget", u"Intruder_Alt", None))
        self.IN_Intruder_Head.setText(QCoreApplication.translate("Widget", u"Intruder_Head", None))
        self.label_16.setText(QCoreApplication.translate("Widget", u"Heading             :", None))
        self.label_17.setText(QCoreApplication.translate("Widget", u"Altitude             :", None))
        self.label_18.setText(QCoreApplication.translate("Widget", u"Hor_velocity     :", None))
        self.label_19.setText(QCoreApplication.translate("Widget", u"Ver_Velocity     :", None))
        self.IN_Intruder_Hor_vel.setText(QCoreApplication.translate("Widget", u"Intruder_Hor_vel", None))
        self.IN_Intruder_Ver_vel.setText(QCoreApplication.translate("Widget", u"Intruder_Ver_vel", None))
        self.label_20.setText(QCoreApplication.translate("Widget", u"ECEF_East         :", None))
        self.label_21.setText(QCoreApplication.translate("Widget", u"Logitude            :", None))
        self.IN_Intruder_y.setText(QCoreApplication.translate("Widget", u"Intruder_y", None))
        self.IN_Intruder_lat.setText(QCoreApplication.translate("Widget", u"Intruder_lat", None))
        self.label_22.setText(QCoreApplication.translate("Widget", u"ICAO_number  :", None))
        self.label_23.setText(QCoreApplication.translate("Widget", u"Latitude             :", None))
        self.IN_Intruder_lon.setText(QCoreApplication.translate("Widget", u"Intruder_lon", None))
        self.IN_Intruder_ICAO.setText(QCoreApplication.translate("Widget", u"Intruder_ICAO", None))
        self.IN_Intruder_x.setText(QCoreApplication.translate("Widget", u"Intruder_x", None))
        self.label_24.setText(QCoreApplication.translate("Widget", u"ECEF_North      :", None))
        self.IN_Intruder_Call.setText(QCoreApplication.translate("Widget", u"Intruder_call", None))
        self.label_25.setText(QCoreApplication.translate("Widget", u"Call_sign            :", None))
        self.label_29.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_30.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_31.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_32.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_33.setText(QCoreApplication.translate("Widget", u"[m/s]", None))
        self.label_34.setText(QCoreApplication.translate("Widget", u"[m/s]", None))
        self.label_35.setText(QCoreApplication.translate("Widget", u"[deg]", None))
        self.label_36.setText(QCoreApplication.translate("Widget", u"[  m  ]", None))
        self.label_38.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic;\">INTRUDER INFORMATION</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Widget", u"Distance Plot", None))
        self.map_change_Down.setText(QCoreApplication.translate("Widget", u"MAP SCALE Down", None))
        self.label_39.setText(QCoreApplication.translate("Widget", u"TIME  :", None))
        self.CurrentTime.setText(QCoreApplication.translate("Widget", u"Current TIME", None))
#if QT_CONFIG(tooltip)
        self.tabWidget_2.setToolTip(QCoreApplication.translate("Widget", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.MAP.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">MAP</span></p></body></html>", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("Widget", u"MAP", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("Widget", u"3D", None))
        self.IN_ROS_TIME.setText(QCoreApplication.translate("Widget", u"ROS_TIME", None))
        self.label_41.setText(QCoreApplication.translate("Widget", u"ROS_TIME       :", None))
        self.label_42.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:14pt;\">ADS-B Distance [m]  :</span></p></body></html>", None))
        self.IN_distance.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p><span style=\" font-size:14pt;\">DIstance</span></p></body></html>", None))
        self.Image_Left.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">LEFT 120deg</span></p></body></html>", None))
        self.Close_Left.setText(QCoreApplication.translate("Widget", u"Close", None))
        self.Open_Left.setText(QCoreApplication.translate("Widget", u"Open", None))
        self.Close_Right.setText(QCoreApplication.translate("Widget", u"Close", None))
        self.Image_Right.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">RIGHT 120deg</span></p></body></html>", None))
        self.Open_Right.setText(QCoreApplication.translate("Widget", u"Open", None))
        self.Image_Front.setText(QCoreApplication.translate("Widget", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">FRONT</span></p></body></html>", None))
        self.Open_Front.setText(QCoreApplication.translate("Widget", u"Open", None))
        self.Close_Front.setText(QCoreApplication.translate("Widget", u"Close", None))
    # retranslateUi

